rsksmart/rif-marketplace-cache

- .dockerignore
- DEPLOYMENT.md
- Dockerfile
- README.md
- config/custom-environment-variables.json5
> docs: deployment guides

- src/rns/hooks/domain.hooks.ts
Solves [View my domains (on sale)](https://rsklabs.atlassian.net/jira/software/projects/RMKT/boards/60?selectedIssue=RMKT-75).
> feat: adds query for owned and placed domains

- config/default.json5
Related to https://github.com/rsksmart/rif-marketplace-dev/issues/19
> feat: change default new-block strategy to polling

- .dockerignore
- Dockerfile
- bin/run
- package.json
- src/sequelize.ts
> Several fixes

- Dockerfile
- src/rns/hooks/domain-offer.hooks.ts
> feat: enables searching my name

- src/rns/hooks/domain.hooks.ts
The sql returns offers details with keys "offers.<field>". Just mapped it to return the offer object that UI expects.
> feat: makes the sql output usable for the ui

- .gitignore
- config/default.json5
- config/development.json5
- package-lock.json
- package.json
- src/rns/index.ts
- src/rns/rns.processor.ts
Few tweaks regarding SQLite support that changes configuration, dependencies etc.
Also workaround for https://github.com/rsksmart/rif-marketplace-cache/issues/103
> SQLite support

- src/rns/hooks/sold-domain.hooks.ts
- src/rns/models/sold-domain.model.ts
- src/rns/models/transfer.model.ts
- src/rns/rns.processor.ts
> fix: new Transfer entity to avoid SoldDomain synchronization problems

- src/rns/hooks/sold-domain.hooks.ts
The query for retrieving sold domains was not converting sellerAddress to lower case and it wasn't using the UI query properly. Now it is:)
Linked to [UI#143](https://github.com/rsksmart/rif-marketplace-ui/pull/143)
> feat: fixes sold query

- src/app.ts
- src/blockchain/index.ts
- src/healthcheck.ts
> feat(core): health-check route

- DEPLOYMENT.md
- Dockerfile
- bin/entrypoint
While there, adjust DEPLOYMENT.md accordingly. Also add an environment
variable in Dockerfile to allow specifying specifics targets for
`precache` subcommand.
> feat: add entrypoint for running required steps

- config/ganache.json5
- config/rsktestnet.json5
* Update contract addresses with the new NFT implementation for Ganache and Testnet
Needs to be merged together with https://github.com/rsksmart/rif-marketplace-ui/pull/190
and  https://github.com/rsksmart/rif-marketplace-dev#46
> fix: new marketplace contract address

- src/services/rns/rns.precache.ts
Fixes issue on a testnet which seems to fail the process of precache on a strange name resolution.
> feat: wrapps storing name in the precache in try

- config/ganache.json5
Adds confirmations for ganache config file.
> fix: add confirmations for rns contracts

- package-lock.json
- package.json
- src/app.ts
- src/services/authentication.ts
- src/services/rns/rns.channels.ts
- src/services/rns/rns.processor.ts
Filters certain channels based on the ownerAddress.
The address needs to be send by client in the authentication process.
Currently filtered channels/services are domains and sold domains.
Notifications are not yet included.
Solves [RMKT-215](https://rsklabs.atlassian.net/browse/RMKT-215?atlOrigin=eyJpIjoiZjMxMzc3ZDZiZjUzNDI4ZjgxNTk4ZDE4ZDAxN2JkZDMiLCJwIjoiaiJ9)
Relates to [UI-PR267](https://github.com/rsksmart/rif-marketplace-ui/pull/267)
> hotfix: directed notifications

- config/ganache.json5
- config/rsktestnet.json5
- package-lock.json
- package.json
- src/definitions.ts
- src/services/rns/index.ts
- src/services/rns/rns.processor.ts
* Bump version of `RNS` contract to `v0.1.2`
* Use new `RNS` simple placement contract - Update Addresses.
* Ignore `Transfers` handler when coming form the Marketplace Contract 
* Process `transfers` related to the Marketplace contract in the `TokenSold` handler.
* Create `registerTransfer` function to avoid code duplication as Transfers are now generated in both handlers.
Works together with UI PR: https://github.com/rsksmart/rif-marketplace-ui/pull/271
Setup and Deploy locally - Dev PR: https://github.com/rsksmart/rif-marketplace-dev/pull/66
> feat: add new RNS contract

- config/default.json5
- src/app.ts
- src/blockchain/index.ts
- src/blockchain/new-block-emitters.ts
- src/blockchain/utils.ts
- src/definitions.ts
- src/store.ts
Add NewBlockEmitter service and expose it on `/new-block` url
> feat: expose new-block event

- package-lock.json
- package.json
- src/cli/precache.ts
- src/cli/purge.ts
- src/services/storage/index.ts
> feat: awaiting for store to save all data

- config/ganache.json5
* Add Storage contract address  for `ganache`
> feat: add storage config info for ganache

- config/default.json5
- package-lock.json
- package.json
- src/services/storage/models/agreement.model.ts
- src/services/storage/models/offer.model.ts
filter out offers without `peerid`
Closes #255 and closes #253
> feat: apply storage contract changes

- config/rsktestnet.json5
* Update RNS contract in Testnet
> feat: rns contract testnet

- config/default.json5
Fixed typo preventing event handle execution
> fix: TotalCapacitySet topic sig typo

- config/rskmainnet.json5
* Add config file for `mainnet` including contract addresses and starting blocks.
> feat: mainnet config file

- .gitignore
- config/ganache.json5
- eslintrc.js
- src/services/storage/handlers/offer.ts
- src/services/storage/hooks/offers.hooks.ts
- src/services/storage/models/offer.model.ts
This PR will allow the UI to filter storage offers by the average price of their billing plans.
To achieve this it calculates the mean price when in the `BillingPlanSet` event handler and stores it in a field `averagePrice`.
This PR also adds changes to the storage hooks that allow consumer to filter the storage records.
Resolves cache requirements for [RMKT-247](https://rsklabs.atlassian.net/jira/software/projects/RMKT/boards/60?assignee=5e84f3015b08780c1c4127b0&selectedIssue=RMKT-247)
Blocking [RMKT-29](https://rsklabs.atlassian.net/browse/RMKT-29)
> feat(storage): filtering

- README.md
Lets write up basic troubleshooting guide on our day-to-day problems! Additional suggestions are welcomed, or you can just push them directly to this branch!
> docs: troubleshooting ideas

- config/ganache.json5
* Add staking contract address in Ganache config file.
> feat: add staking address

- src/services/rns/hooks/domain-offer.hooks.ts
- src/services/rns/hooks/domain.hooks.ts
- src/services/rns/hooks/sold-domain.hooks.ts
- src/services/rns/index.ts
Adds pagination
Contributes towards https://github.com/rsksmart/rif-marketplace-ui/issues/384
Works in tandem with https://github.com/rsksmart/rif-marketplace-ui/pull/389
> feat(rns): pagination for mainnet release

- config/ganache.json5
- package-lock.json
- package.json
- test/integration/utils.ts
* Bumps version for `storagerManager` and updates address.
> chore: update storage contracts and addresses

- src/services/storage/index.ts
- test/integration/services/storage/storage-manger.spec.ts
Extend `Stake` GET API with `array` of stakes: `{ totalStakedFiat: number, stakes: Array<Stakes> }`
> feat: adjust stake get endpoint

- src/services/storage/handlers/stake.ts
- src/services/storage/index.ts
- src/services/storage/models/stake.model.ts
- test/integration/services/storage/storage-manger.spec.ts
- test/unit/services/storage/processor.spec.ts
Add aggregated total stake in USD to stake update event
> feat(staking): add total-staked-usd to stake update event

- src/services/rns/hooks/domain-offer.hooks.ts
- src/services/rns/hooks/domain.hooks.ts
- src/services/rns/hooks/sold-domain.hooks.ts
- src/services/rns/index.ts
* feat: adds pagination
* feat: allows paginations oveerride from client
* refactor: freshens up
* refactor: makes use of discardQuery
* fix: ensures hook chaining
Co-authored-by: Juraj Piar <juraj@iovlabs.org>
> feat(rns): integrate RNS from mainnet release

- config/ganache.json5
- package-lock.json
- package.json
- test/integration/utils.ts
* Uses new version of `StorageManager` contract
* Updates address for `ganache`
> feat: new storage contract

- config/staging.json5
* Adds config file for `staging` environment.
> chore: adds config for staging environment

- config/ganache.json5
* Adds Comms default configuration for `ganache`
> chore: add comms configuration for ganache

- config/ganache.json5
- config/staging.json5
* Add `networkId` parameter for `ganache` and `staging` config files.
> chore: add networkId for ganache and staging

- README.md
- config/default.json5
- config/ganache.json5
- config/staging.json5
- package-lock.json
- package.json
* New contract version `v6`
* Updates addresses for ganache and staging.
> chore: new contract and config

- README.md
- src/services/storage/models/offer.model.ts
- src/services/storage/utils.ts
- test/integration/services/storage/storage-manger.spec.ts
- test/unit/services/storage/models.spec.ts
Related to https://github.com/rsksmart/rif-marketplace-ui/issues/464
> feat(storage): moves average price of offers to monthly basis

- src/communication/handlers.ts
- test/integration/services/storage/storage-manger.spec.ts
> feat: add agreement exceed limit notification to provider

- config/default.json5
- src/communication/handlers.ts
- src/definitions.ts
- src/errors.ts
- src/utils.ts
- test/integration/utils.ts
- test/unit/services/storage/communication.spec.ts
implement retry with timeout mechanism for async function
> fix: handle libp2p messages which comes before agreement event

- config/rsktestnet.json5
* Adds new addresses for Storage in Testnet
* Enables service in Testnet.
> chore: new Testnet addresses

- config/rsktestnet.json5
* Adds bootnode configuration for Testnet
> chore: bootnode config for Testnet

- .gitignore
- Dockerfile
- README.md
- bin/entrypoint
- config/custom-environment-variables.json5
- config/default.json5
- config/test.json5
- src/app.ts
- src/cli/db-migration.ts
- src/cli/start.ts
- src/db-backup.ts
- src/definitions.ts
- src/sequelize.ts
- src/utils.ts
- test/integration/utils.ts
- test/unit/cli.spec.ts
- test/unit/db-backup-restore.spec.ts
> feat: datadir support

- src/services/storage/models/offer.model.ts
- src/services/storage/utils.ts
- test/unit/services/storage/models.spec.ts
- test/unit/services/storage/services.spec.ts
Related to [RMKT-486](https://rsklabs.atlassian.net/browse/RMKT-486)
> fix(storage): calculates availableCapacity ignoring inactive agreements

- package-lock.json
- package.json
- src/services/rns/index.ts
Resolves #484
No real changes were done in Cache, all the changes comes from web3-events, from PR https://github.com/rsksmart/web3-events/pull/54
> chore: update web3-events

- config/ganache.json5
> chore: ganache contract addresses

- config/rsktestnet.json5
* Increase confirmations for Testnet
> chore: confirmations for testnet

- .circleci/config.yml
- .tasegir.js
- README.md
- config/custom-environment-variables.json5
- config/development.json5
- config/ganache.json5
- config/test.json5
- package-lock.json
- src/services/authentication.ts
- test/unit/services/rns/processor.spec.ts
> chore: fix security issues

- config/rsktestnet.json5
- config/staging.json5
Adds `rif` token for Testnet  and Staging configuration.
> chore: add rif token config testnet
