rsksmart/rif-marketplace-cache

package.json

Oclif has specified path where to look for commands in the package.json.
In development environment it should look into the /src/ path, but for
released packages it has to be into compiled folder /lib/. There is some
magic in Oclif that should make this work, but it does not work properly
so it needs to be changed manually.
Hacky fix is replacing this value before releasing to NPM and then
returning this value after release if finished.

fix(cli): oclif release command path modification

---

src/blockchain/events.ts

Web3.js uses for getPastEvents() for both fromBlock and toBlock equal
comparsion, hence one needs to be incremeted.

fix(blockchain): polling right block numbers

---

src/rns/hooks/domain-offer.hooks.ts
src/rns/hooks/domain.hooks.ts
src/rns/hooks/sold-domain.hooks.ts

The rns event processor stores token ids without leading zeroes, using utility [numberToHex](https://github.com/rsksmart/rif-marketplace-cache/blob/master/src/rns/rns.processor.ts#L52).
This causes an issue when wanting to compare the sha3 of a search term (for searching domain by name) with the stored tokenIds.
For quick resolution I use the numberToHex function to create the same hex string format for the queries. This seems to be an unnecessary computation but we can fix that in the refactor.

fix: makes domain name sha3 to hex w/o lead 0s

---

src/rns/hooks/domain.hooks.ts

After adding the sold status to offers (btw, why not just delete the record?) the query was not including those records for the users that bought the domain.
Adding to the pile, this extends the raw sql query to also include the 'SOLD' offers in the owned domains query.
Disclaimer: Although the query will have to be cleaned up, rather sooner than later, at the moment the priority lays with getting it work. Refactor will come later.

fix: includes bought domains in the query

---

src/definitions.ts
src/services/rates/index.ts
src/services/rns/hooks/domain-offer.hooks.ts
src/services/rns/hooks/domain.hooks.ts
src/services/rns/hooks/sold-domain.hooks.ts
src/services/rns/index.ts
src/services/rns/models/domain-offer.model.ts
src/services/rns/models/domain.model.ts
src/services/rns/models/expiration.model.ts
src/services/rns/rns.processor.ts
src/services/storage/index.ts

Closes #131
Closes #93 
Plus extracts expiration date from domains in order to prevent racing condition on blockchain transfer events.
Makes a tiny refactor of services' paths in the definitions and rns.
Sold process doesn't seem to work yet (though triggered) and transfer events seem to be only triggered in precache, thus the PR is a draft.
Otherwise seems to be working fine.

feat: adds expiration table and removes status from offers

---

src/services/rns/hooks/domain-offer.hooks.ts
src/services/rns/hooks/domain.hooks.ts
src/services/rns/models/domain.model.ts
src/services/rns/models/expiration.model.ts
src/services/rns/models/owner.model.ts
src/services/rns/rns.precache.ts
src/services/rns/rns.processor.ts

adds id to expiration table definition
As I had a different version of the ui-config that was generated by the dev project, I was missing the auction registrar address and thus did not capture the error in my last PR.
This is to fix the issue with foreign key constraints when writing to domains table.

fix: makes precache update expiration before domain table

---

README.md

This should help the user to understand and thus properly setup the Cache configuration.

feat: adds link to node-config documentation

---

src/blockchain/confirmator.ts
test/blockchain/confirmator.spec.ts

If there are processed mutiple blocks in one confirmation invokation
some events could be skipped over.

fix(core): confirmations are handled for multiple blocks

---

src/app.ts
src/logger.ts

This was suggestion from Vojtech as mitigation of the "node-config" related problems as this will display your current configuration on startup.

feat: display current configuration on startup

---

config/rsktestnet.json5
package-lock.json
package.json
src/services/rns/index.ts

* Use the new version of the NFTS contract (`0.1.1`). This requires to change the way the `ABI` is processed (now matches all the other contracts). 
* Also updated the Testnet address for the contract using the new deployed address.
Closes #203

chore(rns): bump version for RNS contract

---

src/services/rns/hooks/domain-offer.hooks.ts
src/services/rns/hooks/domain.hooks.ts
src/services/rns/models/domain-offer.model.ts
src/services/rns/models/sold-domain.model.ts
src/services/rns/rns.processor.ts

- adds priceString to represent price in string format for the UI to consume
- excludes price (number) from results
Relates to [UI-PR-251](https://github.com/rsksmart/rif-marketplace-ui/pull/251)
Addresses [#RMKT-268](https://rsklabs.atlassian.net/browse/RMKT-268)
Closes #133

feat: addresses the issue with malformed price

---

config/default.json5
src/blockchain/events.ts
src/blockchain/utils.ts
src/definitions.ts
test/blockchain/events.spec.ts

Adds support for listening topics, which will filter only those events from contract that we are interested in. If the Contract emits other events that we are not interested then they will be ignored directly by the blockchain node and won't be even fetched to Cache.

feat(core): support listening on topics

---

config/ganache.json5
config/rskmainnet.json5
config/rsktestnet.json5
config/test.json5
package-lock.json
package.json
src/blockchain/utils.ts
src/services/rns/rns.processor.ts
test/services/rns/processor.spec.ts
test/utils.ts

* Decode domain names when processed in Batch. This requires processing the internal transactions of the TX data field, using RLP and following the `FifsRegistrar` encoding.)
* Add support and configuration for the RNS Batch Registration contract (in all environments).
* Test for transaction decoding in Batch Mode (Registering two domains).

feat: batch support for domain registration

---

config/custom-environment-variables.json5
config/default.json5
config/development.json5
config/ganache.json5
config/test.json5
package-lock.json
package.json
src/cli/start.ts
src/db-backup.ts
src/definitions.ts
src/sequelize.ts
src/services/storage/handlers/stake.ts
src/services/storage/hooks/offers.hooks.ts
src/services/storage/hooks/stakes.hook.ts
src/services/storage/index.ts
src/services/storage/models/offer.model.ts
src/services/storage/models/stake.model.ts
src/services/storage/storage.channels.ts
src/services/storage/storage.processor.ts
src/store.ts
test/cli.spec.ts
test/services/storage/models.spec.ts
test/services/storage/processor.spec.ts
test/utils.ts

This PR introduces listening and handling of Staking Contract Events

feat(storage): staking support

---

src/services/storage/index.ts
test/integration/services/storage/storage-manger.spec.ts

Solves the problem of returning "NaN" when trying to get the stakes for an account without funds

fix: return total staked fiat as 0.00 for empty account

---

package.json

Puts the `--watch` argument back to the bin script in _package.json_
Resolves #380

fix(dev): re-adds the watch arg to bin script

---

src/services/storage/models/agreement.model.ts

It seems that `lastPayout.getTime()` is 5 minutes ahead of `Date.now()`. This fix defaults to 0 when that time is bigger than now

fix(storage): makes periodsSinceLastPayout 0 if not positive

---

config/default.json5

* Adds Topics for RNS to `default` configuration
* `ExpirationChanged(uint256,uint)` is defined in the contract using `uint256` and `uint` for each parameter. Although these represent the same data type I kept the same naming as the Contract. But I wasnt sure if here we should keep it like this or use `uint256` in both params.  Here is the definition:  https://github.com/rnsdomains/rns-rskregistrar/blob/94b7226c29a2c76cb5f234c86a1a0fc8ff600aba/contracts/NodeOwner.sol#L17
Closes #244

chore: topics for RNS events

---

config/staging.json5

* Updates correct block number for `staking` contract in Staging.

chore: block number for staking contract

---

config/ganache.json5

* Adds default Bootnodes for Ganache when deploying locally.

chore: add boot nodes for ganache

---

config/ganache.json5

* Add `RIF` token configuration which is used in `ganache` and deployed correctly by DEV project.

chore: adds tokens in ganache config

---

README.md

I just noticed there was an overlap on the description of the `averagePrice` endpoint but didn't want to mess unrelated things in the other PR so this PR fixes that

docs: fixes endpoints descriptions

---

.dockerignore
Dockerfile
README.md
src/@types/colors/index.d.ts
src/logger.ts

Resolves #417 
Uses the `supportsColor()` and also allows env. variable override.

fix(core): logs colors handling

---

src/services/storage/utils.ts
test/unit/services/storage/services.spec.ts

When calculating the availableCapacity I was wrongly grouping by `offerId`. We should group by `provider` that's the primary key for offers table

fix(storage): groups by provider to get min max available capacity

---

config/rsktestnet.json5

* Increase confirmations in Testnet. Based on feedback from Core team, we should at least consider 5 confirmations as minimum. We can use this for Testnet and then plan for 6-8 confirmations on Mainnet to be on the safe side.
Will do same change for Storage Pinner

chore: increase confirmations Testnet

---

CHANGELOG.md
package.json

- update `web3-events` lib (reorg handling issue)

chore: release version v1.3.1

---

config/default.json5

* Disable ordering of events for RNS for now as this is causing issues with confirmations and it is not really mandatory.

chore: disable order of events

---

CHANGELOG.md
package.json

- change tables name from dash to underscore
- disable order processing of events for RNS

chore: release version v1.3.2

---

src/logger.ts
test/unit/logger.spec.ts

Affected Assets
https://github.com/rsksmart/rif-marketplace-cache/releases/tag/v1.3.2
Description
Log Injection (also known as Log Forging) is a vulnerability where an attacker can forge new log entries, due to a bad input sanitisation by the application.
Remediation
All external data should be sanitised before sending it to logs.
When using a simple one line per entry format for the logs, new lines characters should be removed or escaped so that an attacker cannot create new entries.
References
https://owasp.org/www-community/attacks/Log_Injection
https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html
https://thesecurityvault.com/appsec/log-forging-vulnerability-and-how-to-fix-it/

chore: fix potential log injection

---

CHANGELOG.md
config/rsktestnet.json5
config/staging.json5
package.json

<a name="1.3.3"></a>
* **rns:** adds post find pagination hook ([#529](https://github.com/rsksmart/rif-marketplace-cache/issues/529)) ([4f72426](https://github.com/rsksmart/rif-marketplace-cache/commit/4f72426b9acf538b57077999caf1eb0db23594fa))
* **rns:** removes pagination ([759ad55](https://github.com/rsksmart/rif-marketplace-cache/commit/759ad55f6200a093457b4bfce909813413d135fd))
* do not expose error stack trace to client ([#556](https://github.com/rsksmart/rif-marketplace-cache/issues/556)) ([6ae31d4](https://github.com/rsksmart/rif-marketplace-cache/commit/6ae31d4b43262d181ca1f946ae1218e5dfea36f8))
* **rns:** adds filter by fiat to offers ([58cca7c](https://github.com/rsksmart/rif-marketplace-cache/commit/58cca7cdbec1cf13843dab00273c72843a410449))
* **rns:** copies and adapts …

Release 1.3.3

---

CHANGELOG.md
package-lock.json
package.json

* **build:** fix typescript compilation ([#560](https://github.com/rsksmart/rif-marketplace-cache/pull/560))

Release 1.3.4
